import React from 'react';
import { Marker, Popup } from 'react-leaflet';
import '../styles/Map.css';
import { useTranslation } from 'react-i18next';
import {
  doctors,
  fast_food,
  bank,
  bar,
  cafe,
  restaurant,
  school,
  theatre,
  police,
  atm,
  car_wash,
  charging_station,
  clinic,
  dentist,
  hospital,
  kick_scooter_parking,
  kindergarten,
  library,
  payment_centre,
  pharmacy,
  post_box,
  post_office,
  recycling,
  shelter,
  university,
  veterinary,
  waste_disposal,
  biergarten,
  food_court,
  ice_cream,
  pub,
  college,
  dancing_school,
  driving_school,
  first_aid_school,
  language_school,
  surf_school,
  toy_library,
  research_institute,
  training,
  music_school,
  traffic_park,
  bicycle_parking,
  bicycle_repair_station,
  bicycle_rental,
  bicycle_wash,
  boat_rental,
  boat_sharing,
  bus_station,
  car_rental,
  car_sharing,
  compressed_air,
  vehicle_inspection,
  driver_training,
  ferry_terminal,
  fuel,
  grit_bin,
  motorcycle_parking,
  parking,
  parking_entrance,
  parking_space,
  taxi,
  weighbridge,
  payment_terminal,
  bureau_de_change,
  baby_hatch,
  nursing_home,
  social_facility,
  arts_centre,
  casino,
  cinema,
  community_centre,
  conference_centre,
  events_venue,
  exhibition_centre,
  fountain,
  music_venue,
  nightclub,
  planetarium,
  public_bookcase,
  social_centre,
  studio,
  courthouse,
  fire_station,
  post_depot,
  prison,
  ranger_station,
  townhall,
  bbq,
  bench,
  dog_toilet,
  dressing_room,
  drinking_water,
  give_box,
  mailroom,
  parcel_locker,
  shower,
  telephone,
  toilets,
  water_point,
  watering_place,
  sanitary_dump_station,
  waste_basket,
  waste_transfer_station,
  animal_boarding,
  animal_breeding,
  animal_shelter,
  animal_training,
  baking_oven,
  clock,
  crematorium,
  dive_centre,
  funeral_hall,
  grave_yard,
  hunting_stand,
  internet_cafe,
  kitchen,
  kneipp_water_cure,
  lounger,
  marketplace,
  monastery,
  photo_booth,
  place_of_mourning,
  place_of_worship,
  public_bath,
  public_building,
  refugee_site,
  vending_machine,
} from './Icons';
const Markers = ({ placeName, lat, lng, distance, address, name }) => {
  const iconMapping = {
    doctors: doctors,
    fast_food: fast_food,
    bank: bank,
    bar: bar,
    cafe: cafe,
    restaurant: restaurant,
    school: school,
    theatre: theatre,
    police: police,
    clinic: clinic,
    dentist: dentist,
    atm: atm,
    car_wash: car_wash,
    charging_station: charging_station,
    hospital: hospital,
    kick_scooter_parking: kick_scooter_parking,
    kindergarten: kindergarten,
    library: library,
    payment_centre: payment_centre,
    pharmacy: pharmacy,
    post_box: post_box,
    post_office: post_office,
    recycling: recycling,
    shelter: shelter,
    university: university,
    veterinary: veterinary,
    waste_disposal: waste_disposal,
    biergarten: biergarten,
    food_court: food_court,
    ice_cream: ice_cream,
    pub: pub,
    college: college,
    dancing_school: dancing_school,
    driving_school: driving_school,
    first_aid_school: first_aid_school,
    language_school: language_school,
    surf_school: surf_school,
    toy_library: toy_library,
    research_institute: research_institute,
    training: training,
    music_school: music_school,
    traffic_park: traffic_park,
    bicycle_parking: bicycle_parking,
    bicycle_repair_station: bicycle_repair_station,
    bicycle_rental: bicycle_rental,
    bicycle_wash: bicycle_wash,
    boat_rental: boat_rental,
    boat_sharing: boat_sharing,
    bus_station: bus_station,
    car_rental: car_rental,
    car_sharing: car_sharing,
    compressed_air: compressed_air,
    vehicle_inspection: vehicle_inspection,
    driver_training: driver_training,
    ferry_terminal: ferry_terminal,
    fuel: fuel,
    grit_bin: grit_bin,
    motorcycle_parking: motorcycle_parking,
    parking: parking,
    parking_entrance: parking_entrance,
    parking_space: parking_space,
    taxi: taxi,
    weighbridge: weighbridge,
    payment_terminal: payment_terminal,
    bureau_de_change: bureau_de_change,
    baby_hatch: baby_hatch,
    nursing_home: nursing_home,
    social_facility: social_facility,
    arts_centre: arts_centre,
    casino: casino,
    cinema: cinema,
    community_centre: community_centre,
    conference_centre: conference_centre,
    events_venue: events_venue,
    exhibition_centre: exhibition_centre,
    fountain: fountain,
    music_venue: music_venue,
    nightclub: nightclub,
    planetarium: planetarium,
    public_bookcase: public_bookcase,
    social_centre: social_centre,
    studio: studio,
    courthouse: courthouse,
    fire_station: fire_station,
    post_depot: post_depot,
    prison: prison,
    ranger_station: ranger_station,
    townhall: townhall,
    bbq: bbq,
    bench: bench,
    dog_toilet: dog_toilet,
    dressing_room: dressing_room,
    drinking_water: drinking_water,
    give_box: give_box,
    mailroom: mailroom,
    parcel_locker: parcel_locker,
    shower: shower,
    telephone: telephone,
    toilets: toilets,
    water_point: water_point,
    watering_place: watering_place,
    sanitary_dump_station: sanitary_dump_station,
    waste_basket: waste_basket,
    waste_transfer_station: waste_transfer_station,
    animal_boarding: animal_boarding,
    animal_breeding: animal_breeding,
    animal_shelter: animal_shelter,
    animal_training: animal_training,
    baking_oven: baking_oven,
    clock: clock,
    crematorium: crematorium,
    dive_centre: dive_centre,
    funeral_hall: funeral_hall,
    grave_yard: grave_yard,
    hunting_stand: hunting_stand,
    internet_cafe: internet_cafe,
    kitchen: kitchen,
    kneipp_water_cure: kneipp_water_cure,
    lounger: lounger,
    marketplace: marketplace,
    monastery: monastery,
    photo_booth: photo_booth,
    place_of_mourning: place_of_mourning,
    place_of_worship: place_of_worship,
    public_bath: public_bath,
    public_building: public_building,
    refugee_site: refugee_site,
    vending_machine: vending_machine,
  };

  const markerIcon = iconMapping[placeName];
  const { t } = useTranslation();

  return (
    <Marker
      className="markerContainer markerSquare"
      position={[Number(lat), Number(lng)]}
      icon={markerIcon}
      riseOnHover={true}
    >
      <Popup>
        <div>
          <strong>{name}</strong>
        </div>
        <div>{address}</div>
        <div>
          <strong>{t('Distance')}:</strong>{' '}
          {distance < 1000
            ? `${distance.toFixed(0)}m`
            : `${(distance / 1000).toFixed(1)}km`}
        </div>
      </Popup>
    </Marker>
  );
};

export default Markers;
